### ISSUE TITLE
warning on console while running

### ISSUE THREAD

**Issue by divyanshupathak** [gabrielpoca/meteor-redux-demo#3]
Hello,
I simply clone this example and run and this give me the error. Please take a look at below screenshot.

![screenshot from 2017-03-29 18 50 18](https://cloud.githubusercontent.com/assets/19850600/24456468/ba514c2c-14b0-11e7-8779-33f9fc1ecc71.png)
 Any suggestion.
Thanks

**Comment by gabrielpoca** [comment]
Hi @divyanshupathak , I just pushed a fix for it 👍
