### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by suryaiiit** [gabrielpoca/meteor-redux-demo#4]
I tried to work out this with ReactNative but then I got stuck at "client/setup.js",

Tracker.autorun(() => {
  store.dispatch({
    type: 'SET_MESSAGES',
    messages: Messages.find().fetch(),
  });
});

I could not get the Messages.find().fetch() - work :(, any suggestions??

Thank you.

**Comment by gabrielpoca** [comment]
Hi @suryaiiit thank you for opening an issue. I don't work with react native, so I'm not sure what could be happening. Do you think maybe the Messages collection doesn't exist at the time this runs?

**Comment by suryaiiit** [comment]
Thanks for the response, If I've the answer I'll update here.

**Comment by gabrielpoca** [comment]
Thank you 👍
